version: "3.8"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT:3307:3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
